version: "3.7"
services:
    core-api-v2-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: core-api-v2-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "127.0.0.1:4491:80"
        environment:
            APP_URL: "https://localhost:4491"
            APP_NAME: "CORE-API-V2"
        networks:
            - core-api-v2-net

networks:
    core-api-v2-net:
        driver: bridge
