version: "3.7"
services:
    core-soto-api-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: core-soto-api-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "127.0.0.1:4491:80"
        environment:
            APP_URL: "https://localhost:4491"
            APP_NAME: "SOTOAYAM-CORE-API"
        networks:
            - core-soto-api-net

networks:
    core-soto-api-net:
        driver: bridge
